### ISSUE TITLE
Some bullet lists get exported as definition lists

### ISSUE THREAD

**Issue by ngm** [openrepair/datastandard#3]
e.g.

![image](https://user-images.githubusercontent.com/172324/145023742-39f4594b-3cc5-4ee8-aa1a-9d47a3e2fb49.png)

instead of

![image](https://user-images.githubusercontent.com/172324/145023661-a896d539-0c7d-441a-a72e-f9d899cbfb3a.png)

The corresponding sources looks like:

```
<ul class="simple">
<li><dl class="simple">
<dt>Create a joint approach to documenting successes and challenges with</dt><dd><p>post-warranty repairs</p>
</dd>
</dl>
</li>
<li><dl class="simple">
<dt>Promote it as a standard available to other community repair</dt><dd><p>networks, and in the future to commercial repairers and others
collecting repair data</p>
</dd>
</dl>
</li>
<li><dl class="simple">
<dt>Enable coalition members and others to use the data from our joint</dt><dd><p>work to produce insights, with the objective of demanding more
repairable products, improved support and access to better repair
services</p>
</dd>
</dl>
</li>
<li><dl class="simple">
<dt>Jointly explore additional information we can all collect to help</dt><dd><p>make a stronger case for increased repairability</p>
</dd>
</dl>
</li>
</ul>
```

For some reason sphinx is attempting to output definition lists.

**Comment by ngm** [comment]
Also spotted here:

![image](https://user-images.githubusercontent.com/172324/145024051-b49d23d3-f936-4c6e-a1e2-472f66999b53.png)

and here

![image](https://user-images.githubusercontent.com/172324/145024102-0f8eab89-cd88-4c54-b499-e5a9adb6c019.png)

**Comment by zenlan** [comment]
Markup for the above has been fixed, the html regenerated and pushed
